name: "Hello World Action"
description: "My first custom GitHub Action"
author: "Bayarmaa"
inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"
runs:
  using: "node20"
  main: "index.js"
