name: Expressions and Contexts
on: 
  issues:
    types: [labeled]

jobs:
  expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Run only if issue has a bug label
        if: contains(github.event.issue.labels.*.name, 'bug')
        run: echo ${{ join(github.event.issue.labels.*.name, ', ') }}
      - name: Expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ true }}
          echo ${{ false }}
          echo ${{ null }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ 1 && 0 }}
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
          echo '${{ toJson(secrets) }}'