name: Second Workflow Demo
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run a String
        run: echo "This is the second workflow!"
      - name: Run a multi-line script
        run: |
          node -v
          npm -v

  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: Check macOS version
        run: sw_vers

  dependent-job:
    runs-on: windows-latest
    needs: [run-shell-command, parallel-job-macos]
    steps:
      - name: Echo a string
        run: Write-Output "This job runs after the other two jobs complete."
